# Conclusion

To explore the arrest records in NYC during 2022, specifically from January 1, 2022 to September 30, 2022, we drew several graphs to understand the pattern of crimes that happened in NYC this current year after slightly cleaning and transforming the data set. Through exploring the demographics and biometric data with histograms, it is remarkable that the number of male perpetrators highly outweighs the number of female perpetrators. The majority of perpetrators are in their 25 to 44 years old. In addition to age and gender, the distribution of race of perpetrators is not uniform as well. The common types of crimes are related to assault and offenses. Through the mosaic plot, surprisingly, there is no strong relationship between the categories of crime and the suspects, and the types of crimes are not gender-specific, race-specific, or age-specific in general. Furthermore, location is a factor in the number of crimes, so it is reasonable to say that some districts are relatively safer than others. Besides, the crimes are not time-dependent. There is no daily or monthly pattern in the number and types of arrests over time. With the interactive histogram of the monthly number of arrests over time, there is a weekly pattern each month, which is consistent with the observation from the heatmap among the months, the day of the week, and the number of crimes.
When it comes to the limitations of our exploration of arrest records in NYC this year, we only use the interactive histogram plots to show the daily number of arrests each month. We acknowledge that the interactive map is an efficient way to visualize the location of the crime and help the audience understand the pattern more directly. Besides, this time we focused on the current year's data, so we didn’t have the opportunity to compare this year’s arrest records and the historical records. The such comparison might help us observe if there is any improvement in terms of public safety and police services over time. Due to the limitation of time and workload during the final week, unfortunately our group didn’t have much time to explore this dataset more deeply and advance our data visualization techniques. One of the most important lessons we learned from this project is that start doing the project early, try to clean and transform the data as tidily as possible, and explore the dataset with multiple plots and techniques. Then we can find a suitable way to visualize and understand the dataset efficiently and effectively.
In the future, with a more flexible time span and opportunities to improve the skillsets regarding R and exploratory data analysis, our group will combine the current year’s arrests data with historical data and compare the yearly patterns and changes over time. Moreover, we plan to use more map plots to visualize the relationships among locations, the number of crimes, types of crimes, and so on. Ideally, our group will add more interactive elements in the graphs so that the audience can explore the dataset more freely. 
