--- 
title: "Exploration of Arrest Records in NYC"
author: "Lingjun Zhang, Yijia He, Junyuan Huang"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The crime rate in New York has been the topics for many years. According to NYPD statistics, the number of crimes in New York City increased from 8,906 in July 2021 to 11,619 in July 2022, an increase of 30.5 percent. Almost all types of crime increased last month. The number of high-profile subway crimes also continues to rise, with Manhattan topping the list among the five boroughs. Meanwhile, a surge in shootings in Brooklyn, Southern Queens and Staten Island also increased the number of shootings citywide from 157 in July last year to 178 this year, a 13.4 percent increase. 
 
On enforcement, NYPD officers in October 2022 made 4,367 arrests for complaints of major felony crimes, a 16.5% increase over the 3,749 arrests for major felonies in the same month last year. Arrests for major felonies are up 25.8% (39,742 v. 31,582) so far in calendar 2022, compared with the first 10 months of 2021. “Keeping New Yorkers safe is our mission – and the NYPD’s commitment to the public will never waver,” said Police Commissioner Keechant L. Sewell. “Our work to suppress violence, to maintain order on our streets and in our subway stations is intelligence-driven, flexible, and focused on prevention. Our officers are elevating their work every day – particularly in the subway system where the public is seeing our visible presence, extensive coverage in trains and platforms, and more engagement with riders and those who work in the system.”

With the historical analysis of the arrest records in NYC, our article considers the ongoing debate over crime rates in different districts, portrait of a crime figures, as the next potential crisis for the NYPD. The paper concludes with a discussion of methods that could assist the police in deploying police forces, faster implementation of arrest operations, and improve urban security.