# Proposal

## Research topic
In this project, we will explore the arrests records in NYC during the current year. It is well known that New York has a high crime rate in the country. How Newyork's police deal with it and what we can do to improve the efficiency of polices' work? Here, we will analyze the portraits of Perpetrators arrested in New York State, including their age and gender. Also, we will gathering the information about the arrest actions like the frequency of arrests by region. All these information can provide effective data, help the police to locate suspects more quickly when a crime is committed, and assist the police to understand the criminal psychology of the offender. At the same time, it can also assist the police in deploying police forces, faster implementation of arrest operations, and improve urban security.



## Data availability
We will mainly explore the arrest record data in New York City during the current year. We extract the data from New York OpenData (https://data.cityofnewyork.us/Public-Safety/NYPD-Arrest-Data-Year-to-Date-/uip8-fykc), which is a free public data source published by New York City agencies and other organizations. The data we will use is collected by the New York Police Department(NYPD), including information about the type of crime, the location, the demographics of perpetrators, and so on. The Office of Management Analysis and Planning extracts and reviews the data every quarter. The data is last updated on Oct 19, 2022. 

The dataset is categorized as public safety and contains 141,000 observations with 19 columns in a structured form. Each row represents an arrest effected in New York City by NYPD. The column shows the basic information about the arrest, including the time, location, and level of offense. At the same time, the dataset also contains descriptions of perpetrators, such as gender, age, race, etc. Based on these data, we can well accomplish our research goals.

We can export the datasets in CSV format for offline use from New York OpenData. Then we can import and manipulate the CSV formatted data in R from the local path.






####
Meanwhile, we will also compare the current year's arrest information with the past to get the changes in the crime rate in New York City in recent years. We obtain the historic data from the same platform New York OpenData  (https://data.cityofnewyork.us/Public-Safety/NYPD-Arrests-Data-Historic-/8h9b-rp9u). This dataset has the same format as year-to-date data, making it easy to compare with each other. The historic dataset is last updated on June 9, 2022.

We can export these two datasets in CSV format for offline use from New York OpenData. Then we can import and manipulate the CSV formatted data in R from the local path.

